### ISSUE TITLE
סרוויס לניהול האירועים

### ISSUE THREAD

**Issue by MIK837** [MuSeek-WebApp/server#10]
1. שמירה של אירוע חדש
2. עדכון אירוע קיים
3. מחיקת אירוע קיים
4. הוספה של להקה/אמן לאירוע
5. עדכון סטטוס של להקה/אמן לאירוע - הלוגיקה אמורה להיות שילוב של מה היה הסטטוס הקודם ומי 
    עשה זאת: 
    1. בעל העסק יזם והוסיף את הלהקה - הבקשה נמצאת על הלקה לצורך אישור/דחייה
    2. הלהקה יזמה וביקשה להתווסף לאירוע - הבקשה נמצאת על בעל העסק לצורך אישור/דחייה
    3. הלהקה אישרה את הבקשה להצטרך לאירוע - הבקשה נמצאת על בעל העסק לצורך 
        אישור/דחייה
    4. הלהקה דחתה את הבקשה להצטרך לאירוע - הבקשה נמצאת על בעל העסק בסטטוס לא 
        משתתף
    5. בעל העסק אישר את השתתפות הלהקה באירוע - הלהקה תשתתף באירוע - נשלח מייל ללהקה 
        עם הפרטים של האירוע ותזכורת
    6. בעל העסק דחה את השתתפות הלהקה באירוע - הבקשה נמצאת על בעל העסק בסטטוס לא 
        משתתף 
6. מחיקה של להקה/אמן מאירוע - מחיקה לגמרי מהאירוע (לא מקרה של דחיה)
7. שליפה של המידע של אירוע קיים - כל המידע מוצג לכולם באותה מידה חוץ מרשימת המשתתפים
    1. יוצר האירוע רואה הכל (כל הסטטוסים וכל הבקשות לאירוע)
    2. יוזר לא רלוונטי לאירוע רואה את רשימת המשתתפים המאושרים באירוע 
    3. להקה/אמן שרלוונטיים לאירוע (לא משנה באיזה סטטוס - כולל נדחה) רואים את עצמם עם 
        הסטטוס המתאים ואת כל המשתתפים המאושרים באירוע

מניחה שרוב הדברים עשית כבר כחלק מהפיתוח אבל לוודא שיש הכל - בנוסף נראלי את הקטע עם מי יכול לראות מה לא דיברנו על זה אבל די חשוב רלוונטי גם לגבי הפעולות שכל אחד יכול לבצע על כל הרשימה (לדוגמא מחיקה של אמן זה רק הבעל עסק שיצר את האירוע)

**Comment by omerfinger** [comment]
צריך להוסיף גם שליפה עבור להקה שרוצה לראות את הREQUESTS שמחכים לה .
ושליפה של הREQUESTS של עסק

**Comment by MIK837** [comment]
יש להוסיף שליפה של כל האירועים החדשים שנוספו 
יש לאפשר להציג זאת לפי סינון של 
שם המקום, טווח תאריכים, זאנר,מיקום, דירוג של המקום
