### ISSUE TITLE
הוספה של לוגיקה של ביקורות על היוזר

### ISSUE THREAD

**Issue by MIK837** [MuSeek-WebApp/server#21]
ציון, כותרת, תיאור, מי הזין, מתי הוזן
לכל יוזר נשמור מערך שישמור כמה ציון 1,2,3,4,5 כוכבים יש לו - בכל עדכון שקשור לזה נעדכן את המערך עבור היוזר.

1. הוספה של ביקורת חדשה לדיבי - הוספה למערך
2. עדכון של ביקורת בדיבי - עדכון של המערך
3. מחיקה של ביקורת בדיבי - הורדה מהמערך
4. שליפה של כל הביקורות על היוזר ממויין לפי החדש ביותר
5. שליפה של כל הביקורות על היוזר ממויין לפי הביקורות הגבוה ביותר
6. שליפה של כל הביקורות של היוזר ממויין לפי הנמוך ביותר

**Comment by Yossig** [comment]
שינוי רייטינג ללייקים
